from .descriptor_templates import descriptor_templates as invoice_descriptor_templates
from .graphic_templates import graphic_templates as invoice_graphic_templates
from .value_templates import value_templates as invoice_value_templates
