from .descriptor_templates import descriptor_templates as qr_invoice_descriptor_templates
from .descriptor_templates import (
    qr_part_descriptor_templates as qr_invoice_qr_part_descriptor_templates,
)
from .graphic_templates import frame_template as qr_invoice_frame_template
from .graphic_templates import qr_part_frame_template as qr_invoice_qr_part_frame_template
from .graphic_templates import scissors_template as qr_invoice_scissors_template
from .graphic_templates import swiss_qr_code_template as qr_invoice_swiss_qr_code_template
from .value_templates import value_templates as qr_invoice_value_templates
from .value_templates import qr_part_value_templates as qr_invoice_qr_part_value_templates
